// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvuihejzsirfblmgwysj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dWloZWp6c2lyZmJsbWd3eXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NjI5NDEsImV4cCI6MjA1NjAzODk0MX0.fNxm-KZ_7woPC3IGq9A1Zs53FXd5jzCNSal9_skMnJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);